fix: stream return EOF when openai return error
sashabaranov/go-openai pull request #184
Opened 2023-03-20 12:45 UTC by liushuangls

fix #173

2023-03-20 13:40 UTC, sashabaranov requested changes
Thank you for the PR! 🔥 Looks good overall, but there are a couple of comments. Would you be able to fix those?

2023-03-20 17:11 UTC, sashabaranov commented on chat_stream.go
> +		if writeErr := stream.errAccumulator.write(line); writeErr != nil {
We can cover this with tests if we make `errorAccumulator` an interface and provide failing one like here https://github.com/sashabaranov/go-openai/blob/aa149c1bf8ccd77403e07fdb7b0122f27d4c9b6b/request_builder_test.go#L30

2023-03-21 16:15 UTC, sashabaranov commented on unmarshaler.go
> +type unmarshaler interface {
Should we use that instead of json.Unmrashal?

2023-03-22 05:32 UTC, sashabaranov approved these changes

2023-03-22 05:32 UTC, merged

2023-03-30 04:01 UTC, juggli commented
nice. I meet the same EOF error in v1.5.2.