Feat/messages api
sashabaranov/go-openai pull request #546
Opened 2023-11-07 20:35 UTC by urjitbhatia

This branch implements [thread messages API](https://platform.openai.com/docs/api-reference/messages)

2023-11-08 02:52 UTC, zhangpeihaoks commented
i real need this pl merge,this help me so more

2023-11-09 06:56 UTC, henomis commented
Hi, to cover your tests you need to add entries in `TestCases` in `client_test.go`

2023-11-09 09:04 UTC, henomis requested changes

2023-11-09 09:04 UTC, henomis commented on messages.go
> +	FileIds     []interface{}    `json:"file_ids"`
```suggestion
	FileIds     []string    `json:"file_ids"`
```

2023-11-09 09:04 UTC, henomis commented on messages.go
> +	Text MessageText `json:"text"`
```suggestion
	Text *MessageText `json:"text,omitempty"`
	ImageFile *ImageFile `json:"image_file,omitempty"` // <- define this one
```

2023-11-10 15:40 UTC, wti806 commented
May I ask when the message API would be ready?

2023-11-10 21:05 UTC, urjitbhatia commented
Thanks, I'll work on the fixes this weekend.

On Fri, Nov 10, 2023, 9:40 AM Ti Wang ***@***.***> wrote:

> May I ask when the message API would be ready?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sashabaranov/go-openai/pull/546#issuecomment-1805960644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJLOR344QSLRTGXNR2EFS3YDZDHTAVCNFSM6AAAAAA7BZOV7OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBVHE3DANRUGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-11 23:52 UTC, urjitbhatia commented
> TestCases

Adding the test cases...

However, when looking at these tests - It makes sense to push for a high coverage but some of the work done to keep it high seems forced. For example, covering the branch when the API returns an error.

I'd suggest rethinking the requirement a little bit - it makes sense to cover the main logic but this test seem to add very little or no value - https://github.com/sashabaranov/go-openai/blob/master/client_test.go#L184 - am I missing something in the value of this test? It doesn't actually test that the request building failed due to bad/missing params, only that an `if err` was added to the calls - lmk if that's the intended use anyways.

@henomis @sashabaranov

2023-11-12 12:16 UTC, sashabaranov commented on messages.go
> +	Annotations []interface{} `json:"annotations"`
let's use `any` instead of `interface{}`

2023-11-12 12:21 UTC, sashabaranov commented on messages.go
> +	urlSuffix := fmt.Sprintf("/threads/%s%s%s", threadID, messagesSuffix, encodedValues)
Just a suggestion: changing `messagesSuffix` from `/messages` to `messages` would make formatting more consistent without `%s%s` mixed with `%s/%s`

2023-11-12 12:54 UTC, sashabaranov commented
@urjitbhatia thank you so much for the PR! A couple of minor additions and let's merge it 🙌🏻 

> However, when looking at these tests - It makes sense to push for a high coverage but some of the work done to keep it high seems forced. For example, covering the branch when the API returns an error.
> I'd suggest rethinking the requirement a little bit - it makes sense to cover the main logic but this test seem to add very little or no value - https://github.com/sashabaranov/go-openai/blob/master/client_test.go#L184 - am I missing something in the value of this test? 

You know, when I started working on this library a couple of years earlier, I would agree with you. I didn't see any point in extensive testing except for integration tests with the actual API to check that the client actually works. 

Now, I have come to realise a couple of things about testing:

- It's easy to test the "happy path", but to test error cases, you need to design the code with clear interfaces and separation of concerns (`RequestBuilder` and `ErrorAccumulator` are good examples of that)
- You are either forcing code coverage or dealing with the code base with a constant decline of code coverage sometime in the future. I would prefer the former, especially for such a widely-used library
- ~100% code coverage makes it simpler to accept changes into the codebase — it's just easier to trust the code that way

I think the requirement of copy-pasting [3 lines](https://github.com/sashabaranov/go-openai/pull/546/files#diff-4dc56e64f310cd8c12bb00f75c09e83f5d875563ea9901788e525487dc6788b3R304-R306) of tests per client method is a reasonable requirement for all these benefits.

So I think the way forward is to actually reach 100% coverage, add more randomisation(see #491), fuzzing, and integration tests in CI.

> It doesn't actually test that the request building failed due to bad/missing params

Currently the validation happens on the OpenAI backend side, I'll be happy to accept any client validation though 👍🏻

2023-11-12 20:56 UTC, urjitbhatia commented
@sashabaranov added the style fixes from the last review :)

2023-11-13 03:46 UTC, 496672097 commented
"I need help. How can I obtain the result of a run after executing the CreateRun() method?"
![image](https://github.com/sashabaranov/go-openai/assets/20740855/19ad1917-b3c6-4da9-b9c2-d745944bc871)

2023-11-13 07:39 UTC, vsumit89 commented
HI @sashabaranov @urjitbhatia any updates by when this PR will be merged. 
Thanks for all the work you guys have been putting in!

2023-11-13 14:33 UTC, sashabaranov approved these changes

2023-11-13 14:33 UTC, merged

2023-11-14 15:26 UTC, lowczarc commented
Any reason why `withBetaAssistantV1()` has not been added here ? https://github.com/sashabaranov/go-openai/pull/546/commits/17673a12f5e939f46c64a4761ffd786795aba1aa#diff-a24c457dd8089cef80ea36580edebca6e5dac3a6b277909fffe3cced7c5ba812L69

When using CreateMessage I get an error `You must provide the 'OpenAI-Beta' header to access the Assistants API. Please try again by setting the header 'OpenAI-Beta: assistants=v1'`

2023-11-14 15:30 UTC, lowczarc commented on messages.go
> +	req, err := c.newRequest(ctx, http.MethodPost, c.fullURL(urlSuffix), withBody(request))
Any reason for not adding `withBetaAssistantV1()` here ? When using CreateMessage I still get the error `You must provide the 'OpenAI-Beta' header to access the Assistants API. Please try again by setting the header 'OpenAI-Beta: assistants=v1'.`